// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZGP7eCNa5TUrE2yCQK5NReAfKbnhjrW4',
    appId: '1:155751119935:web:26d4861ea4749eaf908c8a',
    messagingSenderId: '155751119935',
    projectId: 'restauranteb-83ab7',
    authDomain: 'restauranteb-83ab7.firebaseapp.com',
    storageBucket: 'restauranteb-83ab7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2ZCvRrvcPeCvXfwKeBwsBvod-NBxHhS0',
    appId: '1:155751119935:android:a58f418811b756d4908c8a',
    messagingSenderId: '155751119935',
    projectId: 'restauranteb-83ab7',
    storageBucket: 'restauranteb-83ab7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBPney6uTX_2R9bEz8tcOWqZry3yRM5Yo',
    appId: '1:155751119935:ios:d002056941695787908c8a',
    messagingSenderId: '155751119935',
    projectId: 'restauranteb-83ab7',
    storageBucket: 'restauranteb-83ab7.appspot.com',
    iosBundleId: 'com.example.learning',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBPney6uTX_2R9bEz8tcOWqZry3yRM5Yo',
    appId: '1:155751119935:ios:d002056941695787908c8a',
    messagingSenderId: '155751119935',
    projectId: 'restauranteb-83ab7',
    storageBucket: 'restauranteb-83ab7.appspot.com',
    iosBundleId: 'com.example.learning',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZGP7eCNa5TUrE2yCQK5NReAfKbnhjrW4',
    appId: '1:155751119935:web:945f68a4edd0fcf2908c8a',
    messagingSenderId: '155751119935',
    projectId: 'restauranteb-83ab7',
    authDomain: 'restauranteb-83ab7.firebaseapp.com',
    storageBucket: 'restauranteb-83ab7.appspot.com',
  );
}
